# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
