# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_auto_20170910_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastmessagestatus',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
